# Generated by Django 2.1.7 on 2020-09-30 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaUpload',
            fields=[
                ('filename', models.TextField(db_column='FileName')),
                ('presentationmaterial_ptr', models.OneToOneField(db_column='ID', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.PresentationMaterial')),
            ],
            options={
                'db_table': 'PresentationMediaUpload',
            },
            bases=('reports.presentationmaterial',),
        ),
        migrations.CreateModel(
            name='MediaUploadType',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('private_storage_type', models.TextField(db_column='PrivateStorageType')),
                ('public_storage_type', models.TextField(db_column='PublicStorageType')),
            ],
            options={
                'db_table': 'SummitMediaUploadType',
            },
        ),
        migrations.AddField(
            model_name='mediaupload',
            name='type',
            field=models.ForeignKey(db_column='SummitMediaUploadTypeID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_uploads', to='reports.MediaUploadType'),
        ),
    ]
