# Generated by Django 2.1.7 on 2022-04-11 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='moderator',
            field=models.ForeignKey(db_column='ModeratorID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderated_presentations', to='reports.Speaker'),
        ),
    ]
