# Generated by Django 2.1.7 on 2021-10-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='class_name',
            field=models.TextField(db_column='ClassName', default=''),
        ),
    ]
