# Generated by Django 2.1.7 on 2019-05-27 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RsvpTemplate',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.TextField(db_column='Title')),
                ('enabled', models.BooleanField(db_column='Enabled')),
            ],
            options={
                'db_table': 'RSVPTemplate',
            },
        ),
        migrations.AlterField(
            model_name='summitevent',
            name='abstract',
            field=models.TextField(db_column='Abstract', null=True),
        ),
        migrations.AlterField(
            model_name='summitevent',
            name='category',
            field=models.ForeignKey(db_column='CategoryID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='reports.EventCategory'),
        ),
        migrations.AlterField(
            model_name='summitevent',
            name='location',
            field=models.ForeignKey(db_column='LocationID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='reports.AbstractLocation'),
        ),
        migrations.AlterField(
            model_name='summitevent',
            name='summit',
            field=models.ForeignKey(db_column='SummitID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='reports.Summit'),
        ),
        migrations.AlterField(
            model_name='summitevent',
            name='type',
            field=models.ForeignKey(db_column='TypeID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='reports.EventType'),
        ),
        migrations.AddField(
            model_name='rsvpquestion',
            name='template',
            field=models.ForeignKey(db_column='RSVPTemplateID', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reports.RsvpTemplate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summitevent',
            name='rsvp_template',
            field=models.ForeignKey(db_column='RSVPTemplateID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='reports.RsvpTemplate'),
        ),
    ]
