# Generated by Django 5.0.3 on 2024-10-03 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_selection_plan_and_session_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectionplan',
            name='type',
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='lightning_count',
            field=models.IntegerField(db_column='LightningCount', default=0),
        ),
        migrations.AddField(
            model_name='speaker',
            name='big_photo_id',
            field=models.IntegerField(db_column='BigPhotoID', null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='photo_id',
            field=models.IntegerField(db_column='PhotoID', null=True),
        ),
        migrations.CreateModel(
            name='SelectedPresentationList',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('class_name', models.TextField(db_column='ClassName', default='')),
                ('list_type', models.TextField(db_column='ListType', default='')),
                ('list_class', models.TextField(db_column='ListClass', default='')),
                ('category', models.ForeignKey(db_column='CategoryID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_presentation_lists', to='reports.eventcategory')),
                ('member', models.ForeignKey(db_column='MemberID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_presentation_lists', to='reports.member')),
                ('selection_plan', models.ForeignKey(db_column='SelectionPlanID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_presentation_lists', to='reports.selectionplan')),
            ],
            options={
                'db_table': 'SummitSelectedPresentationList',
            },
        ),
        migrations.CreateModel(
            name='SelectedPresentation',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('class_name', models.TextField(db_column='ClassName', default='')),
                ('order', models.IntegerField(db_column='Order')),
                ('collection', models.TextField(db_column='Collection')),
                ('member', models.ForeignKey(db_column='MemberID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_presentations', to='reports.member')),
                ('presentation', models.ForeignKey(db_column='PresentationID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_presentations', to='reports.presentation')),
                ('list', models.ForeignKey(db_column='SummitSelectedPresentationListID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_presentations', to='reports.selectedpresentationlist')),
            ],
            options={
                'db_table': 'SummitSelectedPresentation',
            },
        ),
    ]
