# Generated by Django 2.1.7 on 2020-10-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200930_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='company',
            field=models.TextField(db_column='Company', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='phone_number',
            field=models.TextField(db_column='PhoneNumber', max_length=50, null=True),
        ),
    ]
