# Generated by Django 2.1.7 on 2020-11-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20201120_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='location',
            field=models.TextField(db_column='Location', null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='browser',
            field=models.TextField(db_column='Browser', null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='ip',
            field=models.TextField(db_column='Ip', null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='origin',
            field=models.TextField(db_column='Origin', null=True),
        ),
    ]
