# Generated by Django 2.1.7 on 2022-08-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20220411_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='summitevent',
            name='created',
            field=models.DateTimeField(db_column='Created', default=None, null=True),
        ),
    ]
