# Generated by Django 2.1.7 on 2020-10-16 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20201015_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('url', models.TextField(db_column='URL')),
                ('color', models.TextField(db_column='Color')),
                ('city', models.TextField(db_column='City')),
                ('state', models.TextField(db_column='State')),
                ('country', models.TextField(db_column='Country')),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='EventMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_ptr', models.OneToOneField(db_column='ID', on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='reports.Metric')),
                ('event', models.ForeignKey(db_column='SummitEventID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='reports.SummitEvent')),
            ],
            options={
                'db_table': 'SummitEventAttendanceMetric',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('type', models.TextField(db_column='Type')),
                ('ip', models.TextField(db_column='Ip')),
                ('origin', models.TextField(db_column='Origin')),
                ('browser', models.TextField(db_column='Browser')),
                ('ingress_date', models.DateTimeField(db_column='IngressDate')),
                ('outgress_date', models.DateTimeField(db_column='OutgressDate')),
                ('location', models.TextField(db_column='Location')),
            ],
            options={
                'db_table': 'SummitMetric',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('order', models.IntegerField(db_column='Order')),
                ('company', models.ForeignKey(db_column='CompanyID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='reports.Company')),
                ('summit', models.ForeignKey(db_column='SummitID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='reports.Summit')),
            ],
            options={
                'db_table': 'Sponsor',
            },
        ),
        migrations.CreateModel(
            name='SponsorMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_ptr', models.OneToOneField(db_column='ID', on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='reports.Metric')),
                ('sponsor', models.ForeignKey(db_column='SponsorID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='reports.Sponsor')),
            ],
            options={
                'db_table': 'SummitSponsorMetric',
            },
        ),
        migrations.CreateModel(
            name='SponsorshipType',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('order', models.IntegerField(db_column='Order')),
                ('name', models.TextField(db_column='Name')),
                ('label', models.TextField(db_column='Label')),
                ('size', models.TextField(db_column='Size')),
            ],
            options={
                'db_table': 'SponsorshipType',
            },
        ),
        migrations.AddField(
            model_name='sponsor',
            name='type',
            field=models.ForeignKey(db_column='SponsorshipTypeID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='reports.SponsorshipType'),
        ),
        migrations.AddField(
            model_name='metric',
            name='member',
            field=models.ForeignKey(db_column='MemberID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='reports.Member'),
        ),
        migrations.AddField(
            model_name='metric',
            name='summit',
            field=models.ForeignKey(db_column='SummitID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='reports.Summit'),
        ),
    ]
