# Generated by Django 2.1.7 on 2020-10-16 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20201016_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmetric',
            name='id',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='location',
        ),
        migrations.RemoveField(
            model_name='sponsormetric',
            name='id',
        ),
        migrations.AlterField(
            model_name='eventmetric',
            name='metric_ptr',
            field=models.OneToOneField(db_column='ID', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.Metric'),
        ),
        migrations.AlterField(
            model_name='sponsormetric',
            name='metric_ptr',
            field=models.OneToOneField(db_column='ID', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.Metric'),
        ),
    ]
